### ISSUE TITLE
SIL-LSP API Integration - C-1

### ISSUE THREAD

**Issue by coolkang** [coolkang/pwaaweb#1]
WBS: C-1

Schedule to call SIL-LSP API weekly and cache the current result into database.

- Need to understand SIL-LSP response and create a corresponding document structure in database(MongoDB)
- Implement a module to call the API and cache the result weekly into database. It should be structured into two components: scheduler & API specific interface.
- Scheduler is a component that is neutral to any API services and it is used to schedule to call a specific API service.
- The API interfaces will handle a certain API specific request and response: it knows how to make a call to a certain API service and how to parse the response. It also handles how to store an extracted data from the response into a database.
- The schedule should allow to change the period of schedule like weekly, bi-weekly, and monthly.

** Please refer to API documents

**Comment by coolkang** [comment]
Please include the below attributes to SIL API collection (table) so that these attributes can be queried later in other modules.

- iso_name
- reference_name
- ethnologue_name
- existing_scripture
- existing_scripture_dis
- update_date_time

**Comment by coolkang** [comment]
Please look at that you can use mongodb connection parameters from settings.py

**Comment by coolkang** [comment]
When using connections, try-catch may need to be used...?

**Comment by esanzy** [comment]
There are two types of collection: History and Latest Data. When scheduled python script fetches data from remote API, it adds response json text to History Collection and updates Latest Data Collection.

in Update Procedure,
key is 'iso_name', so, data would be overwritten when row has same key(iso_name).
and key is new, then row would be added.

**Comment by coolkang** [comment]
One more thing to enhance when Latest Data collection is updated...

There can be multiple records for one language in API response. Before updating the collection, please check if update_data_time for each record in response is later than the corresponding record in collection. If so, update the record in collection, otherwise, ignore it.

**Comment by coolkang** [comment]
Ian,

Please create a cronjob and test if this is working.

**Comment by YongHoJang** [comment]
hi

**Comment by YongHoJang** [comment]
1차 개발 완료 , 커밋 했습니다.

**Comment by coolkang** [comment]
Tested and verified. Close this item.
