### ISSUE TITLE
Implementing a time trend graph for bible translation status - F-2

### ISSUE THREAD

**Issue by coolkang** [coolkang/pwaaweb#11]
WBS: F-2

From a bible translation history table, create a time trend graph and display it on About page.
The time trend graph (line graph) will show:
- The number of translated Bibles
- The number of translation in progress
- The number of not-engaged languages
- A user can choose a time period for this statistics between month vs. year. (At the beginning, we may not have enough history data yet.)

The total number of bible translation status:
- Also, as part of statistics, show the number and % of translated bibles verses not-translated ones.  

![31d70a6e-f57a-11e4-9622-11eb06b8b9cd](https://cloud.githubusercontent.com/assets/2165109/7596004/25fd66fa-f8b0-11e4-8dd7-ec01cf90eb52.png)

**Comment by coolkang** [comment]
To Ian:

Dev is done. Please test this one.

**Comment by Towermonger** [comment]
Spent time testing the page and graph, found no issues.

**Comment by coolkang** [comment]
Close this item.

**Comment by YongHoJang** [comment]
comment 

c3차트: http://c3js.org/

1. Translated Bibles: Bible   BI" > Whole Bible 
2..Translation in progress: 진행중(Abridgement ,New Testament Portions   New Testament   Bible   New Testament with OT portions   Old Testament Portions  Portitions in Old and New Testaments)
3. Not-engaged languages: None  NO" > No Bible
