### ISSUE TITLE
Browse page

### ISSUE THREAD

**Issue by Towermonger** [coolkang/pwaaweb#12]
User navigates to site URL.
User clicks on the "Browse" tab.
System navigates to the "Browse page".
System Checks the database and populates the browse columns with the current data.

User clicks on an entry in the column.
System opens right side result panel and shows the SIL record data for selected entry.

User Clicks "Whole bible" radio button.
System removes all records that don't have Whole Bible code. 
System will only repopulate the result panel once a record has been selected.

Page elements:
- Logo
- Map, Browse, About tab selector
- Login button
- Country, Island, etc. drop down menu
- Bible Translation Status: Radio buttons
- Reset Filter button
- Search Box and submit button
- Language Columns
- Result panel

**Comment by coolkang** [comment]
Here is a new UI mockup. Please look at filters at the top.

- Filters will include "Search", Dropdownload of countries & islands, and Bible Translation Status.

![screen shot 2015-06-08 at 12 04 56 pm](https://cloud.githubusercontent.com/assets/2165109/8040518/cdd0bce8-0dd6-11e5-8684-861075bd33ef.png)

**Comment by coolkang** [comment]
I confirmed that the basic of browse tab has been implemented. Close this item
