### ISSUE TITLE
Map Resizing

### ISSUE THREAD

**Issue by Towermonger** [coolkang/pwaaweb#14]
Currently: When the result panel is opened the map retains size and is shifted off screen to the left. 

Some issues that this creates is that the zoom buttons are no longer accessible, and when zooming with a scroll wheel the map zooms to center which is located just off the left of the screen.

Enhancement: When the result panel is opened the map gets resized to remain fully in screen.

**Comment by coolkang** [comment]
Redundant item. See #13

**Comment by coolkang** [comment]
To: YongHo Jang

상의한데로, 결과 패널의 방식을 오버레이로 바꾸어 주세요.

**Comment by YongHoJang** [comment]
변경했습니다. 확인 부탁합니다.

**Comment by coolkang** [comment]
To: Ian,

Dev is done and please test it.

**Comment by Towermonger** [comment]
Tested, no issues found.
