### ISSUE TITLE
Delete User Bug

### ISSUE THREAD

**Issue by Towermonger** [coolkang/pwaaweb#15]
The below error results when adding a user to a project without entering an email address.

- Create Project
- Add user without entering an email address
- Delete that user
![delete user error](https://cloud.githubusercontent.com/assets/7747759/7985839/c0dad330-0aa1-11e5-89c0-29e4c9bb1ce0.png)

**Comment by coolkang** [comment]
Fixed the issue. Please test this.

**Comment by Towermonger** [comment]
Tested, no issues found.
