### ISSUE TITLE
SIL-LSP: Collect weekly history data of Bible translation status -  F-1

### ISSUE THREAD

**Issue by coolkang** [coolkang/pwaaweb#2]
WBS: F-#1

From a weekly (or scheduled) SIL LSP API call,
Summarize the counts of each status (translated | in progress | not started) and keep the records into a history table with a timestamp.

** All the timestamp should use the standard GMT time for a later conversion to any time zone

**Comment by esanzy** [comment]
TODO : reading flask-celery documents http://flask.pocoo.org/docs/0.10/patterns/celery/

**Comment by coolkang** [comment]
Using celery is a good approach, and with this, we need an independent process running in a server machine to update API cache. So, we may need to think of how to include this in our project. Inside of web app, or out side of this?

**Comment by esanzy** [comment]
pwaaweb/prj/cronjob/weekly.py

register 'python weekly.py' to corntab to run the script weekly
and biweekly.py for biweekly, montly.py for monthly ...

**Comment by coolkang** [comment]
Ian,

Please test this with issue #1

**Comment by Towermonger** [comment]
Observation:
Created job and allowed time to run, received no errors but it seems that the DB didn't update.

How to reproduce:
Created cronjob with the report.py with below comments
    crontab -e
entered below comment in editor
    */15 * * * * /user/bin/PYENV/pwaa/pwaaweb/prj/cronjob/observer/request.py

**Comment by coolkang** [comment]
esanzy,

Please look at the comment by Towermonger. He registered this script as a cron job, but it seems it didn't run, and there is no error message. So, we don't know whether the script has an issue or cronjob registered wrongly. 
Please verify Towermonger's steps above and provide proper steps if needed.

Thanks,

Min Seong

**Comment by esanzy** [comment]
please test with cronjob/weekly.py,
not cronjob/observer/request.py

**Comment by Towermonger** [comment]
Observation:
Created Cronjob with weekly.py
After the script ran I checked the DB there was no pwaa db updated.
There were no messages to indicate what was wrong.
I ran weekly.py independently and got an error saying 403 forbidden. Error seems to come from request.py line# 23 .

![image](https://cloud.githubusercontent.com/assets/7747759/7278211/f7a21dba-e8e1-11e4-847c-3c91c2ea3508.png)

**Comment by coolkang** [comment]
Esanzy,

My question is that if you run weekly.py in cronjob, how does it get required libraries from virtualenv folder. If you run weekly.py as an independent script, you won't activate virtualenv and won't get libraries installed inside of the virtualenv.

The first error that Ian reported will be related with libraries issue. Please check it and let us know.

**Comment by coolkang** [comment]
To: Yongho Jang

테스트를 한 결과, 수정이 필요한 부분입니다:

SIL history 데이타는 SIL의 데이타를 요약을 해서 한주당 한가지 record를 남기면 됩니다.
이 record는 SIL API 내용중 existing_scripture 를 가지고 각각의 값에 해당하는 언어가 몇개인지만을 기록하면 됩니다. 
예를 들어서,
Bible: 304, New Tastament: 128, No Bible: 322, ...

위와 같은 정보를 db table에 넣어주시면 됩니다.

**Comment by YongHoJang** [comment]
수정하였습니다. sildata_analytics 테이블에  해당 코드별로 카운터를 기록합니다.

**Comment by coolkang** [comment]
To: Ian,

Please test it again and see if the updated script creates "sildata_analytics" table in db, and it is populated with new records.

**Comment by Towermonger** [comment]
Current: Running weekly.py produces a 400 bad request error
Expected: Running weekly.py updates mongodb with "sildata_analytics" table

How to reproduce:
- Registered weekly.py as a cronjob
- No change in dbs
- Attempted to run in Python env
- received 400 error

![screenshot from 2015-06-08 14_14_37](https://cloud.githubusercontent.com/assets/7747759/8041850/361d984a-0de9-11e5-9b53-3e7dcb1b26fa.png)

**Comment by coolkang** [comment]
Ian,

At the moment, you need to hook up with an actual script, not weekly.py. 
So, try sil_lsp_cron.sh with the scheduler.

**Comment by Towermonger** [comment]
Set up cronjob with sil_lsp_cron.sh.

Ran as expected adding "sildata_analytics" table to pwaadb.

Current: Adds "sildata_analytics" table to pwaadb.
Expected: "sildata_analytics" table to pwaadb.

**Comment by coolkang** [comment]
Confirmed and close this issue.
