### ISSUE TITLE
Remove browse filters from a map tab.

### ISSUE THREAD

**Issue by coolkang** [coolkang/pwaaweb#20]
Current behavior: the browse filters show up in a map tab.
Expected behavior: The browse filters does not show up in a map tab. It only shows in a browse tab.

How to reproduce:
- Go to a map tab
- You will see the browse filters (search box, countries dropdown, and bible translation status radio buttons) show up at the top of the map tab. 

현재 지도 탭에서 보이고 있는 브라우즈 필터들을 없애주세요. 브라우즈 필터는 브라으즈 탭에만 나타나야 합니다.

**Comment by YongHoJang** [comment]
적용했습니다.

**Comment by coolkang** [comment]
Confirmed the fix and close this item.
