### ISSUE TITLE
Some of Jesus film resources that are available for a language is missing

### ISSUE THREAD

**Issue by coolkang** [coolkang/pwaaweb#21]
Current behavior: If you choose a language "Abau", it only lists one Jesus Film.
Expected behavior: The language "Abau" has two more videos and these should be listed on result panel.

How to reproduce:
1. For example, go to "Browse" tab and click "Abau" in the languge list.
2. Look at Resource section in a result panel. You will see only one Jesus Film video link.
3. In your browser, type below and see the Jesus Film website. It lists three videos.

http://jesusfilmmedia.org/search-result/language/12296

**Comment by YongHoJang** [comment]
finished

**Comment by coolkang** [comment]
tested and confirmed this fix. Close this.
