### ISSUE TITLE
Import Ethnologue data & Country-Islands data - N-3

### ISSUE THREAD

**Issue by coolkang** [coolkang/pwaaweb#22]
Create a script to import Ethnologue data into a separate collection (table) "EthnologueData".
In the given data file, import column A to O.

The script should also import below fields into a separate collection (table) "CountryIslandLanguage".
- Country_Na, inhibited, islandname, island_ID, islandID, ISO_639
- If islandname field is "No Name*", ignore the record

The script should create another collection (table) for "DigiBible"
- Import "DigiBible" & "ISO_639" field.

**Comment by YongHoJang** [comment]
finished

prj/util/
	ethnologue_data_insert_sh.py    -- sildata merged
	countryisland_language_insert_sh.py

**Comment by coolkang** [comment]
Confirmed this item. Close this issue.
