### ISSUE TITLE
language geography filter for Browse - E-3

### ISSUE THREAD

**Issue by coolkang** [coolkang/pwaaweb#23]
This filter has two categories (Countries & Islands) and create two drop down lists.
- If a user select a country from countries filter, it filter out the language list in a browse tab and also generate a list of islands that belong to the country as a second filter.
- If a user select an island from the second filter, it updates the list of languages in a browse tab.
- When generating a islands list, do not include islands of which "inhibited" field value is "No"

**Comment by coolkang** [comment]
To: Yongho Jang

위의 내용을 번역한 것입니다.

이 개발 아이템은 나라이름과 섬이름을 가지고 두가지 필터를 드롭다운 리스트로 만드는 것입니다.
- 만일 사용자가 나라이름 필터를 사용하여 나라를 선택한 경우 그 나라에 해당하는 언어들만 언어이름 리스트에 보여주세요. 그리고 이와 함께 그 나라에 속한 섬들이름을 가지고 두번째 필터를 드롭다운 리스트로 만들어 주세요.
-  만일 유저가 두번째 필터 (섬들이름)에서 특정한 섬 이름을 선택한 경우, 그 섬에 해당하는 언어들만 메인패널에 있는 언어 리스트에 보여주세요.
- 섬들 이름을 보여주는 필터를 만들때, 데이타상에 "inhibited" 항목이 "No" 인 이름들을 제외시켜 주세요.

**Comment by YongHoJang** [comment]
finished

**Comment by coolkang** [comment]
tested and confirmed. Close this.
