### ISSUE TITLE
Browse search case sensitive 

### ISSUE THREAD

**Issue by Towermonger** [coolkang/pwaaweb#24]
Current: 
Entering input in the search bar without using the correct casing will omit even names that are spelled correctly.

Expected:
When entering input all records that match input regardless of case will appear.

How to reproduce:
Pick any visible name and type it in search without the correct cases and it will not appear.

**Comment by coolkang** [comment]
To: Yongho Jang

현재 브라우즈탭에서 서치를 할때 서치가 대문자 소문자를 구별하는 데요, 이를 사용자가 대문자를 쓰던지 소문자를 쓰던지 상관없이 시스템은 소문자로만 인식을 해서 서치를 했으면 합니다. 
데이타베이스에 있는 언어이름들도 전부 소문자로 인식을 하는 상태에서 사용자의 입력값 (소문자로 전환된)과 매치하는 것을 찾으면 되겠습니다.

**Comment by YongHoJang** [comment]
작업 완료 했습니다.

**Comment by coolkang** [comment]
To Ian,

Developer fixed this issue.
Please test this and close this if it works.

**Comment by Towermonger** [comment]
Tested, no issues found.
