### ISSUE TITLE
Browse filter, Result panel interaction

### ISSUE THREAD

**Issue by Towermonger** [coolkang/pwaaweb#26]
Due to the right most column in the browse tab being blocked by the result panel. 

Enhancement:
Every time that you search or apply a different filter the result panel should close so that all results are visible.

- User selects browse tab
- User clicks on an entry
- System pull result and displays in the result panel
- User applies a new filter
- System updates the total result matching chosen filter and closes the result panel until another record is selected.

**Comment by coolkang** [comment]
To: Yongho Jang,

브라우즈 탭에서 서치박스에 새로 텍스트를 쓰거나 바이블 현황에서 라디오 버튼을 옮기거나 아니면 드롭다운 리스트에서 선택사항을 바꾸면, 현재 열려 있는 결과 창을 닫도록 바꾸어 주세요.

**Comment by YongHoJang** [comment]
finished

**Comment by coolkang** [comment]
To Ian,

Dev is done. Please test this

**Comment by Towermonger** [comment]
Tested, no issues found.
