### ISSUE TITLE
Result Panel Display Update

### ISSUE THREAD

**Issue by coolkang** [coolkang/pwaaweb#29]
To Yongho Jang,

아래 그림처럼 result panel을 업데이트해주세요. 

- 성경번역 현황 내용과 텍스트를 바꾸었습니다.
- 예수영화 링크들이 여러개가 존재하는 경우 첫번째 예수영화 링크 스타일을 반복해서 해주시면 됩니다.
- DigiBible 링크는 데이타베이스 테이블에서 가져오면 됩니다.
- Virtual Storehouse 링크는 기존 URL인 아래 링크에 현재 선택된 언어의 iso code를 {{iso_code}} 대신에 넣으면 됩니다.
> http://virtualstorehouse.org/catalogsearch/result/?q={{iso_code}}

- Scripture Earth 링크는 아래의 URL에 현재 선택된 언어의 iso_code를 name 값으로 넣어주면 됩니다.
> http://www.scriptureearth.org/00i-Scripture_Index.php?sortby=lang&name={{iso_code}}

- 이곳에 사용되는 Virtual Storehouse와 Scripture Earth 링크들의 경우는 성경번역이 Whole Bible과 New Testament의 경우에 링크를 만들어서 보여줍니다.

![screen shot 2015-06-15 at 4 35 12 pm](https://cloud.githubusercontent.com/assets/2165109/8171311/8f017baa-137c-11e5-9096-6d65af45b7cf.png)

**Comment by YongHoJang** [comment]
finished

**Comment by coolkang** [comment]
Tested and confirmed this enhancement. Close this issue.

**Comment by coolkang** [comment]
To Yongho Jang,

위의 그림에 보이는 데로, "Resource"를 "Digital Media Resources"로 바꾸어 주세요

**Comment by YongHoJang** [comment]
done

**Comment by coolkang** [comment]
Confirmed and close this
