### ISSUE TITLE
JFM API Integration - C-2

### ISSUE THREAD

**Issue by coolkang** [coolkang/pwaaweb#3]
WBS: C-2

Schedule to call JFM API weekly and cache the current result into database.

- Need to understand JFM response and create a corresponding document structure in database(MongoDB)
- Implement a module to call the API and cache the result weekly into database. It should be structured into two components: scheduler & API specific interface.
- Scheduler is a component that is neutral to any API services and it is used to schedule to call a specific API service.
- The API interfaces will handle a certain API specific request and response: it knows how to make a call to a certain API service and how to parse the response. It also handles how to store an extracted data from the response into a database.
- The schedule should allow to change the period of schedule like weekly, bi-weekly, and monthly.

** Please refer to API documents

**Comment by coolkang** [comment]
To: YongHo Jang

JFM API를 살펴 보았는데요, 먼저 각 iso_code에 해당하는 languageId의 참조 테이블을 데이타베이스에 만들어서 사용하기로 하고, 다음의 URL을 써서 테이블을 만들면 되겠습니다. 현재 1297개의 언어가 JFM API에 있고, 아래의 방법으로 pagination을 해서 여러번 읽거나:
https://admin.arclight.org/v2/media-languages?page=1&limit=100

아니면 한번에 다 읽어도 되겠습니다.
https://admin.arclight.org/v2/media-languages?page=1&limit=1297

**Comment by YongHoJang** [comment]
수정하셨습니다.  작업 파일은 jfm_code_insert_sh.py  이며 jfm_countries 테이블에 입력됩니다.
중복건 제외하고 1214  정도가 입력 되네요

**Comment by coolkang** [comment]
To: Ian

Please test this script (jfm_code_insert_sh.py) as a scheduled task in Ubuntu. Then, you can check if the process creates "jfm_countries" tables. It contains iso language code (three letter code) and the corresponding languageId that JFM API is using.

**Comment by Towermonger** [comment]
Pulled directory
Created cronjob using (jfm_code_insert_sh.py) set to run every 15 minutes.
(*/15 * * * * /user/bin/PYENV/pwaa/pwaaweb/prj/cronjob/jfm_code_insert_sh.py)

Result after allowed time:
No new dbs appeared. 
Attempted to run alone received error:
python: can't open file 'jfm_code_insert_sh.py': [Errno 2] No such file or directory

Pulled again, directory up to date
Checked for errors and re-ran
Received same error.

**Comment by coolkang** [comment]
Ian,

Your error message seems that the scheduler couldn't locate the script in the location. At the moment, the error is not related with programming yet.

I would like to ask you again to check the path and change the file mode of the jfm_code_insert_sh.py so that other process can access and use the script.

To change access mode, use (in the same folder where you have the file):
>>> chmod 777 jfm_code_insert_sh.py

**Comment by Towermonger** [comment]
Changed permissions on jfm_code_insert_sh.py and tested. 

Entered cronjob, no effect, script did not run.

Attempted to run script from PYENV, all expected changes ran. 

Reproduce:

- crontab -e 
- */1 * * * * /home/tower/PYENV/pwaa/pwaaweb/prj/cronjob/jfm_code_insert_sh.py
(Set to run every one minute) 
- Doesn't run.

**Comment by coolkang** [comment]
To Ian,

I talked with the developer, and this script is not meant to be run standalone. I will move this script to util folder so that it is not confused with other cron job.

One thing we need to test and confirm is that we run this as a standalone script from a terminal and check if it creates jfm_countries table and data in it.

**Comment by Towermonger** [comment]
Tested jfm_code_insert_sh.py in terminal.
Everything ran correctly without error. 

Current: Adds jfm_countries table to the db pwaadb.
Expected: Adds jfm_countries table to the db pwaadb.

**Comment by coolkang** [comment]
Confirmed and close this issue.
