### ISSUE TITLE
Bible Translation filter should include languages from Ethnologue data

### ISSUE THREAD

**Issue by coolkang** [coolkang/pwaaweb#31]
Current Behavior: The total number of languages for each translation status does not add up to 1081 and each filter option (except All) filters only SIL data

Expected Behavior: The bible translation filter should include Ethnologue data as well as SIL.

Match:
> "Full Bible" in Ethnologue --> Whole Bible
> "New Testament" in Ethnologue --> New Testament
> "Portions" in Ethnologue --> Portions in Old and New Testament
> "No Bible" in Ethnologue --> No Bible

**Comment by coolkang** [comment]
To Yongho Jang

현재 성경번역현황 필터가 SIL에만 적용이 되네요. 이 필터는 SIL과 Ethnologue 데이타 모두 적용해서 언어 리스트를 사용자에게 보여주어야 합니다. 위의 데이타값을 갖는 Ethnologue 데이타를 필터링해서 SIL 데이타 필터링 결과와 합쳐주세요. 라디오 버튼이 두 데이타에 모두 적용되어야 합니다.

**Comment by YongHoJang** [comment]
done

**Comment by coolkang** [comment]
Confirmed and close this
