### ISSUE TITLE
Move up the web links to top part of result panel prior to Jesus Film links.

### ISSUE THREAD

**Issue by coolkang** [coolkang/pwaaweb#32]
Move up the web links to top part of result panel prior to Jesus Film links.

And, the web links should show up independently from Jesus Film links.

**Comment by YongHoJang** [comment]
done

**Comment by coolkang** [comment]
아직도 다른 링크들이 예수영화 링크들 다음에 나타나는데요, 이야기 했던 것은 확장이 가능하게 다른 링크들은 따로 섹션을 만들어서 위에 올리고, 그 아래에 예수 영화 링크 섹션을 놓는 것이었습니다. 다시 한번 확인해주세요.

**Comment by coolkang** [comment]
Confirmed and close this item
