### ISSUE TITLE
Map Freeze

### ISSUE THREAD

**Issue by Towermonger** [coolkang/pwaaweb#33]
When you click on "Papeete" / French Polynesia the whole page locks up without populating the result panel. 

To reproduce:
Go to the main page and go to this island 
https://www.google.com/maps/place/Pape'ete,+French+Polynesia/@-17.6418262,-149.4458002,12z/data=!4m2!3m1!1s0x769a3a1c874f6695:0x62d6db532881362b?hl=en

and click on it.

**Comment by coolkang** [comment]
To Yongho Jnag,

테스트해본 결과 위의 경우, 브라으저가 멈추네요. 지도 서버에 보낸 request가 돌아오지 않아서 그런 듯 합니다. 이 부분의 원인을 봐주세요. 그리고, 지도서비스 request에 timeout을 주어서 전체 애플리케이션이 멈추지 않도록 했으면 합니다.

**Comment by YongHoJang** [comment]
- Done 작업완료
	- 에러 원인 
		10개의 동영상 목록을 가져오는데 그 중에 다운로드 url 이 없는것이 있었는데 체크가 안되어서 스크립트 에러가 났었음
	- 처리 결과
		하단 동영상 목록은 10개가 출력되나 플래시 비디오 플레이어 에서 에러나서 상단 내용(Bible Translation Status) 출력안됨
		에러내용:  https://admin.arclight.org/videoPlayerUrl?refId=1_496-jf-0- -> Uncaught SyntaxError: Unexpected identifier 



	- 그외 로딩바(loading bar) 변경 결과
		기존에는 로딩바가 뜰때 mask layer 가 있어서 클릭을 막았었음.
		변경후에는 mask layer 를 remove 하여 로딩 중에도 클릭 가능함.

**Comment by coolkang** [comment]
To Ian,

Bug fix is done, and please test this.

**Comment by Towermonger** [comment]
Tested and confirmed fix. No issues found. Close item.
