### ISSUE TITLE
Browse tab does not show language list when the page is loaded first time.

### ISSUE THREAD

**Issue by coolkang** [coolkang/pwaaweb#40]
Current behavior:
If a user go to a browse tab first time, the language list does not show up

Expected behavior:
The language list of all languages should show up.

How to reproduce:
1. Open a new tab.
2. Go to Pacific Waa application's browse tab
3. See the language list

**Comment by coolkang** [comment]
To Yongho Jang,

브라우즈 탭을 사용자가 처음 열면, 언어리스트 부분이 공백으로 나오고 뜨지 않네요. 한번 봐주세요

**Comment by YongHoJang** [comment]
done

테스트 하면서 주석처리 한걸 안 풀었었네요 ㅠ

**Comment by coolkang** [comment]
Confirmed and close this
