### ISSUE TITLE
Language list arrow has different sizes in a browser.

### ISSUE THREAD

**Issue by coolkang** [coolkang/pwaaweb#42]
현재, 여러개의 언어가 존재하는 경우, 결과창에 언어들을 순서대로 볼 수 있도록 화살표로 된 링크가 있는데요, 이 모양이 브라우저에 따라 다르게 나타납니다. 이를 일정한 크기로 나타나게 바꾸어주세요.

그리고 선택된 언어의 갯수를 나타내는 텍스트도, 한개의 언어가 나타날때에는 (1 language) 라고 표시를 해 주시고, 두 개 이상일 때는, 예를 들어, (2 of 3 languages) 라고 표시해주세요.

**Comment by YongHoJang** [comment]
done - 작업완료

**Comment by coolkang** [comment]
화살표를 누를 수 없는 경우 밝은 회색 아이콘으로 표시를 하고, 화살표를 누를 수 있는 경우에는 푸른색 아이콘으로 표시를 해서 시각적으로 사용자가 클릭할 수 있는 아이콘임을 보여주였으면 합니다.

예를 들어 선택된 언어들중에 마지막 언어 정보를 보여줄때는 오른쪽 화살표를 밝은 회색으로 보여주고, 첫번째 언어를 보여줄때는 왼쪽 화살표를 회색으로 보여주어서 클릭할 수 없는 아이콘임을 표시했으면 합니다.

**Comment by YongHoJang** [comment]
done - 작업완료

**Comment by coolkang** [comment]
confirmed and close this.
