### ISSUE TITLE
Navigation of language list in a result panel does not work if there are more than 5 languages for one polygon.

### ISSUE THREAD

**Issue by coolkang** [coolkang/pwaaweb#44]
Current behavior: Navigation of language list in a result panel does not work if there are more than 5 languages for one poligon.

Expected behavior: Users should be able to go through all the selected languages in a result panel.

How to reproduce:
- Select a polygon having more than 5 languages in a map view around left upper part of PNG.
- Go to the next language in a result panel by clicking an right arrow at the top.
- Sometime, the language info section on the panel is empty and the right arrow does not work when clicked.

**Comment by coolkang** [comment]
To Yongho Jang,

상의한데로, 5-6개 언어가 선택됬을때 결과패널에서 네비게이션이 되지 않는 문제입니다. 살펴봐주세요.

**Comment by YongHoJang** [comment]
done 
완료했습니다. git commit 할때 버전충돌 나서 좀 해멧네요 ㅠ

**Comment by coolkang** [comment]
confirmed and close this.
