### ISSUE TITLE
Browse Tab: Filters UI - E-2

### ISSUE THREAD

**Issue by Towermonger** [coolkang/pwaaweb#6]
WBS: E-2

- System filter default: group names in alphabetical order starting at the top, left to right. "All radio button selected"
- User Clicks on one of the Bible translation status radio buttons (e.g. New Testaments)
- System removes all records that do not have the "New Testament" key in them
- User clicks on the "Portions" Radio button.
- System removes all records that do not have the "Portions" key in them
- User clicks the "All" Radio button
- System resets the browse to the default setting.

![untitled](https://cloud.githubusercontent.com/assets/7747759/7622018/616ab0c8-f999-11e4-9d1c-328c2b1e4c50.png)

**Comment by coolkang** [comment]
Here is a new UI mockup. Please look at filters at the top.

- Filters will include "Search", Dropdownload of countries & islands, and Bible Translation Status.
- Each filter is applied in "OR" relationship. So, a user can choose only one filter at a time.
- "Search" filter is triggered when a user types letters in the text box. Then the other two filters will be reset to the default values.
- Location filter (Countries & Islands) will be triggered when a user drop down the list, Then, the other two filters will be reset to the default values.
- Bible Translation filter will be triggered when a user move a radio button. Then, the other two filters will be reset to the default values.
- When the page is updated with a chosen filter, display the total number of languages selected with the filter.

-  유저가 사용할 필터는 서치 필터, 위치필터 (나라와 섬이름들), 그리고 성경번역 현황 필터입니다.
- 각각의 필터들은 한번에 하나만 사용이 되고 두개 이상의 필터가 동시에 사용되지는 않습니다.
- 서치 필터는 사용자가 텍스트박스안에 글자를 치기 시작하면 활성화되고, 사용자가 버튼을 누리면 적용이 됩니다. 이때 다른 두 필터는 초기값으로 재설정됩니다.
- 위치필터는 사용자가 리스트를 내리기 위해서 오른쪽 화살버튼을 누르면 활성화 되고, 리스트중에 나라이름이나 섬이름을 선택하면 적용됩니다. 이때 다른 두 필터는 초기값으로 돌아갑니다.
- 성경번역현황 필터는 사용자가 라디오 버튼을 옮기면 적용되며, 이때 다른 두 필터는 초기값으로 재설정됩니다.
- 서치 필터의 초기값은 공란이고, 위치필터의 초기값은 모든 지역 (All regions)이고, 성경번역현황 필터는 All입니다.
- 필터가 적용된후에 왼쪽 위에 현재 선택된 언어의 총 개수를 표시해줍니다.

![screen shot 2015-06-08 at 12 04 56 pm](https://cloud.githubusercontent.com/assets/2165109/8040518/cdd0bce8-0dd6-11e5-8684-861075bd33ef.png)

**Comment by coolkang** [comment]
필터부분에 라디오 버튼 선택사항들을 위의 그림에서 보이는 순서대로 배열해주세요.

**Comment by coolkang** [comment]
현재 구현된 기능들에 대해 질문이 있습니다.
- 현재 라디오 버튼 필터를 적용할때, 어떤 때는 페이지가 refresh되기도 하고, 어떤 때는 페이지가 refresh 되지 않고 업데이트가 되는 경우가 있는데요. 왜 그렇죠? 
- browse 페이지 전체를 ajax로 구현하면 좋겠습니다.

**Comment by YongHoJang** [comment]
작업 완료 했습니다.
확인 바랍니다.

**Comment by coolkang** [comment]
I tested and confirmed that this item has been implemented. Close this.
