### ISSUE TITLE
Browse Tab: Search - E-2

### ISSUE THREAD

**Issue by Towermonger** [coolkang/pwaaweb#7]
WBS: E-2

- User inputs search keyword(s) in the search bar (text field). Currently, search supports language names.  
- User clicks a find button.
- System filters the browse options down to only what matches the search in part: Users allowed to type part of language names. For example, if a user types "ab" in the search bar, the language names that contains these two letters will show up on the search page.
- The search filter provides a clean button so that a user can clean up a keyword they typed.

![untitled](https://cloud.githubusercontent.com/assets/7747759/7622016/4ff11c38-f999-11e4-9eab-8e8cff13c069.png)

**Comment by coolkang** [comment]
I tested and confirmed this item. Close this.
