### ISSUE TITLE
Map, Browse, About Tab Selector

### ISSUE THREAD

**Issue by Towermonger** [coolkang/pwaaweb#8]
User clicks "Map" tab
System navigates to the page displaying the map.

User clicks "Browse" Tab
System navigates to the page with all the records listed by name. 

User clicks "About" Tab
System navigates to the page with our information and vision on it.

![untitled](https://cloud.githubusercontent.com/assets/7747759/7622001/2a6938ce-f999-11e4-8a86-0804faa3de92.png)

**Comment by coolkang** [comment]
I confirmed this is done. Close this.
