### ISSUE TITLE
Map, Browse Tab: Result Panel - D-2

### ISSUE THREAD

**Issue by Towermonger** [coolkang/pwaaweb#9]
WBS: D-2

The same result panel will be used in both Map tab & Browse Tab.

<b> Map Tab </b>
User clicks on a polygon in the map.
System gets information for that polygon and populates the result panel with it. 
Populated lines are:
* Language Percentages
* 5 Lines of SIL data that will be named
* Jesus Film link if available

<b> Browse Tab</b>
User clicks on a listing.
System gets information for that listing and populates the result panel with it. 
Populated lines are:
* Language Percentages
* 5 Lines of SIL data that will be named
* Jesus Film link if available

**Comment by coolkang** [comment]
To Yongho Jang:

UI 쪽에서 SIL 데이타를 가져올때 쓸 method를 만들었습니다.

ajax에서 아래의 URL로 언어코드를 parameter로 보내면 json 형식으로 데이타를 받을 수 있습니다. 
/getsildata?iso_code={{ios_code}}

이 프로젝트에 기본적으로 jQuery가 import되어 있습니다. UI쪽을 프로그래밍하실때 jQuery을 되도록 사용해 주시면 좋겠습니다.

**Comment by YongHoJang** [comment]
네 감사합니다. 확인해 보겠습니다.~

2015년 6월 3일 오전 7:21, Min Seong Kang <notifications@github.com>님이 작성:

**Comment by YongHoJang** [comment]
우측 판넬 작업1차 적으로 작업 완료 했습니다

디버깅을 위해서 iso_code 일단 출력 시켰구요
sil 데이터는 3개 정도 밖에 출력할게 없더라구요
jfm  데이터는 코드 12200 으로 고정해서 가져오게 했구요

jfm Description 데이터는   short 로 해 봤더니 2줄 밖에 안 나와서 long 로 출력 시켰는데 조금 기네요
맨 하단에 동영상 이미지 하고 flash 플레이어 출력했고
혹시 몰라서 mp4 동영상 링크 걸었습니다. 

mp4는 클릭하면 모바일은 다운받으면서 보이는지 몰라도
pc 에서는 일단 전부 다운받는 형식으로 되네요

browse 탭에서도 일단 샘플로 첫줄에 링크 걸었습니다

우측 panel 은 공통이라 따로 include 로 뺐습니다.

pull 받아 보시고 안되시면 연락주세요
그럼.

**Comment by coolkang** [comment]
To: Ian

Please test pwaa web focusing on map tab. The result panel is still in development, however, you should be able to interact with a map and get SIL bible translation status from a result panel (on the right).

And please test interaction. I noticed that result panel does not get updated after selecting a polygon on a map several times. please check if it is true in difference browsers.

and any other things you can image, please test UI.

**Comment by Towermonger** [comment]
Tested and logged and solved issues found. Close this item.
